#1. Tạo ServiceAccount
#Tạo một ServiceAccount trong namespace mặc định (hoặc namespace mà bạn cần).
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viettu
  namespace: default
---
# 2. Tạo Role
# Role này sẽ có quyền đọc (get, list, watch), sửa (update, patch), và xóa (delete) trên Pod, Service, và Deployment.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
#3. Tạo RoleBinding
#RoleBinding này sẽ liên kết Role với ServiceAccount.

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: viettu
    namespace: default
roleRef:
  kind: Role
  name: custom-role
  apiGroup: rbac.authorization.k8s.io
---
# Bước 4: Gắn ServiceAccount vào Pod
# Cuối cùng, bạn có thể gắn ServiceAccount vào một Pod hoặc Deployment bằng cách chỉ định trường serviceAccountName.
# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  serviceAccountName: viettu
  containers:
    - name: my-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
---
#Ví dụ với Deployment
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: viettu
      containers:
        - name: my-container
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
# kubectl apply -f serviceaccount.yaml
# kubectl apply -f role.yaml
# kubectl apply -f rolebinding.yaml
# kubectl apply -f pod.yaml
# # hoặc cho Deployment
# kubectl apply -f deployment.yaml
